{% set python_min = "3.9" %}
{% set name = "usgs-strec" %}
{% set version = "2.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/usgs_strec-{{ version }}.tar.gz
  sha256: 797afe0bef293e249024b8578cd6557565ee714178ffb1f5db1f740d4448e14c

build:
  entry_points:
    - regcalc = strec.bin.regcalc:main
    - strec_cfg = strec.bin.strec_cfg:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - setuptools-scm >=3.4
    - cython >=0.29.23
    - numpy
    - pip
  run:
    - python >={{ python_min }}
    - configobj >=5.0.6
    - esi-utils-rupture
    - geopy >=2.2.0
    - numpy >=1.21.0
    - openpyxl >=3.0.9
    - pandas >=1.3.5
    - rasterio >=1.2.10
    - sciencebasepy >=2.0.16
    - typer <0.7.0
    - xlrd >=2.0.1
    - xlsxwriter >=3.0.1
    - xlwt >=1.3.0

test:
  imports:
    - strec
  commands:
    #  We will have to skip pip-check for now b/c of PyPI name mangling bs4 vs Beautiful and zmq vs PyZMQ
    #  - pip check
    - regcalc --help
    - strec_cfg --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://code.usgs.gov/ghsc/esi/strec
  summary: USGS SeismoTectonic Regime Earthquake Calculator (STREC)
  license: LicenseRef-PublicDomain
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - emthompson-usgs
    - ocefpaf
